### PR TITLE
Added cotowali and re-sorted some of the sections

### PR DESCRIPTION
**Pull request by asampal**

### CODE REVIEW

**Comment by i582** [comment]
Hi, @asampal, can you fix CI issues?

**Comment by ttytm** [comment]
Looks like all changes except `VOSCA V Playground` have already been implemented. What do you say @i582 should it be added?

**Comment by i582** [comment]
> Looks like all changes except `VOSCA V Playground` have already been implemented. What do you say @i582 should it be added?

I think yes, why not

**Comment by ttytm** [comment]
K, then I see to update this PR here :+1:  to have it finished

**Review by ttytm — APPROVED** [review]

**Comment by ttytm** [comment]
Co-authoring was not intended...

Tho I recently sometimes encounter the issue when hitting the merge button once and it directly merges without waiting for confirmation or allowing to edit. Maybe it's github refined or my browser, need to investigate.

**Pull request merged**
