### PR TITLE
add article "An introduction to V"

### PR DESCRIPTION
**Pull request by Skn0tt**
I wrote a small article that gives a short introduction to the design decisions made in V.
As V is a very promising project, I'd be happy to see it included here! :D

### CODE REVIEW

**Comment by whoizit** [comment]
just notice, you should update the article
- not `cd v/compiler; make`, but `cd v; make`
- you no longer need to wrap everything in `fn main () {}`
- _HTTP package which just calls cURL under the hood_ - It's not clear. This is relevant only for the _mac_ part of the code on the moment

**Comment by medvednikov** [comment]
These are valid points :)

**Comment by Skn0tt** [comment]
> just notice, you should update the article
> 
> * not `cd v/compiler; make`, but `cd v; make`
> * you no longer need to wrap everything in `fn main () {}`
> * _HTTP package which just calls cURL under the hood_ - It's not clear. This is relevant only for the _mac_ part of the code on the moment

Thanks a lot for the heads-up 😄
I updated the article to include your points.

Apparently, the location of the Makefile changed during the last week.
My local copy of the repo still had it in `/compiler`... V is moving fast 🚀

**Comment by ntrel** [comment]
@Skn0tt
* I agree that V's http.get should be changed to return an optional. There are some other functions that should too, e.g. string.index().
* Note that math.sqrt does *not* return an optional, I think this is acceptable as correct code should never pass a negative argument. Otherwise it forces a check on the result when the programmer should have checked the input instead.

**Comment by ntrel** [comment]
@Skn0tt can you fix this please:
```
// this is the way it works in V:
result := math.sqrt(-1) or {
  // ... handle your error
}
```
`sqrt` returns f64, not an optional. When negative the result is NaN.
https://vlang.io/pkg/math

**Comment by Skn0tt** [comment]
You’re absolutely correct, I chose a flawed example. I will edit the article once I get around to it (sometime later this week).

I was kinda busy the last week and I also kinda forgot about it - so sorry for not answering earlier.

**Comment by Skn0tt** [comment]
I just updated the post and replaced `math.sqrt` with the placeholder `unsafe_function`, which I think is better at illustrating my point.
I mentioned your advice in a foot-note, which I hope you're OK with.

**Comment by Ivo-Balbaert** [comment]
A great article, I enjoyed it very much! 
I add here some minor comments, mostly typo's:

- please change Alexander's name from Medvendnikov into Medvednikov
- 'parantheses' should be 'parentheses' 
- change 'The onyl way' into 'The only way'
- in the code of fn fib_cached, the line:
  	fib(n - 1, mut cache) + fib(n - 2, mut cache) 
should be:
	fib_cached(n - 1, mut cache) + fib_cached(n - 2, mut cache)
- perhaps you can add a main function to make it easier for the novice user:
fn main() {
  mut c := Cache{}
  for n := 0; n < 40; n++ {
    fib_n := fib_cached(n, mut c)
    println('$fib_n')
  }
}
- As an exmaple  should be   As an example

**Comment by Skn0tt** [comment]
Thanks a lot for your feedback, I appreciate it a lot! 😄
I fixed the typo's you pointed out. Thanks again!

**Pull request merged**
